### ISSUE TITLE
Trouble converting gcode to hex

### ISSUE THREAD

**Issue by qcrispin** [DeltaFlo/LaserProjector#4]
Update: got some help from a pro, I wasn't understanding the command in python needed the program, the file to be converted and the output file name.  I still had to tweak the gcode file several times until it would give a .cpp file that had any content.  I ended up deleting all G00 and G01 as well as any spaces between the x and y coordinates.  I haven't used stickfont in years because it was kinda clunky, at least back then.  My experience is gcode usually has gaps between the commands.  I'll try modifying my fusion 360 post processor tomorrow and see if I can get it to output what this converter likes.  I'm planning on making a build video for youtube on this.  Maybe I'll do an overview vid and a more detailed one that covers the more common stumbling blocks people (like me) are having.  Again, thanks so much for making this available.  I'm learning a TON!

Original:
Built it, love it, having trouble converting gcode file with Python. Could use some detailed instructions there as I'm only a novice. When running unmodified convertGcode I get error saying parenthesis are missing after print commands. I've added those and the error is gone but now it prints "Usage: convertGCode.py inputfile.nc outputfile.cpp" which I see at the bottom of the code. I've tried replacing "input" with "input.nc" "input.txt", changing the name of my gcode file accordingly, placing my gcode in the same folder, but am still getting no output file. I'm building this for a demo at a school science fair (I'm on the committee) and would like to project images of the school mascot. I'm very experienced with gcode and CNC and have high confidence I can get a nice image if I can avoid manually translating each x/y to hex. :) Vielen dank fur ihre Arbeit und Hilfe, ich hab Deutchland viel mal besucht, mit meine Frau und auch fur meine Arbeit. Mein Deutsch ist gar nicht flussig aber ich finde meistens gut genug! MfG, - Quint

**Comment by olafthiele** [comment]
Would be great to have the steps you took to get to the output

**Comment by qcrispin** [comment]
Per Olaf's request, here are my notes on how to make the g-code converter work:
1. to run the program you must enter the name of the python convertGCode.py file followed by the name of the file you want to convert followed by the name you want the output file to have.  File extensions are important.  On the command line (in the directory the convert file and file to be converted are on) type "convertGCode.py inputfile.nc outputfile.cpp" minus quotation marks "".  My gcode came from Fusion360 as a .nc file but if I edited it manually it would save as a .txt which needed to be reflected in the command line as inputfile.txt.
2.  Converter is VERY sensitive to g-code format as follows:
 - G0 and G1 don't work, must have G00 and G01.  This is easy with a find/replace command in notepad.
 - G00 will turn the laser off, G01 will turn it on (clever idea on Florian's part).  It does this by making the 8 in 0x8000 (the character right after the x which is the highest bit. This is explained in the Arduino code if you dig enough for it.)  
 - There MUST be X and Y coordinates on each line.  Many g-code posts will only print the X or Y if there is only an X or Y move.  They must both be present.  I ended up manually correcting this in my g-code prior to conversion.
 - X and Y positions must be the only things on that line.  G00 and G01 are on their own lines, followed by the X and Y positions on the next line.  Feed is not used by the converter but if on the same line as X and Y you will get an error.  It's okay to have it on the same line as G01.
- Don't have line numbers, N1, N10, N20.  It doesn't know what to do with them.
- When it works you'll get a few lines ending with SCALE: 4601 meaning it has scaled the output to fit the screen.  You can open the raw hexadecimal output file and look for the 0x8000 turning the laser on at various points.

Hope that helps.  Once you get it working it works really well.  - Quint

**Comment by olafthiele** [comment]
Thanks a lot :-)

**Comment by hondaman900** [comment]
Hi There, could you elaborate more as I'm trying to achieve the same thing (laser project from source GCode). I have the Laser Show project working on my bench.

Is the `convertGCode.py` code available, and if so where? What did you modify in the DeltaFlo project for it to read GCode x/y coordinates and convert them to DAC values, or did you go through a conversion to ILDA files first?

Thanks, any help is much appreciated as I'm trying to figure out the best way to achieve the display of GCode files or a serial stream of GCode data.

Thanks in advance.

**Comment by jojoxyz** [comment]
I'm trying to convert gcode saved as txt.

G00 X38 Y200
G01 X38 Y0
G00 X171 Y200
G01 X171 Y0
G00 X38 Y104
G01 X171 Y104

My steps are:
jojo@ubuntu:~$ python convertGCode.py H1.txt test.cpp

The output in termianl is:
bounding box x: 10000000 0
bounding box y: 10000000 0
scale: -0.00040951

There is only this in the output file

const unsigned short draw_object [] PROGMEM = {            }; 

There are no hex values.
I tried to eliminate the gaps but still the same result.
Can anyone help me?

**Comment by jojoxyz** [comment]
I already understood that. Just read carefully.
gcode must be in the form:

G00
X38 Y200
G01
X38 Y0
G00
X171 Y200
G01
X171 Y0
G00
X38 Y104
G01
X171 Y104

Not in the form of:

G00 X38 Y200
G01 X38 Y0
G00 X171 Y200
G01 X171 Y0
G00 X38 Y104
G01 X171 Y104

**Comment by qcrispin** [comment]
Works when I run it.  Typed everything exactly as you did.  Must be an issue on your machine.  I tried dragging the output file to this thread but it says "We don't support that filetype" so here's the raw code.

const unsigned short draw_object[] PROGMEM = {
0x0,0xfff,
0x8000,0x0,
0xaa3,0xfff,
0x8aa3,0x0,
0x0,0x851,
0x8aa3,0x851,
};

**Comment by jojoxyz** [comment]
Thanks for the effort. I made a bad comment in a previous comment. It already works. The only problem was the gcode script.
But I have another problem. I can't control Python. But I would like one change there.
When your converter translates the file to hex, the laser goes around the line. This causes a radius at the edges of the object. When I create code manually I do it like this

"
0x0, 0x14,         // g0 x0  y20
0x8012, 0x1e,   // g1 x18 y30
0x12, 0x1e,       // g0 x18 y30
0x8012, 0x18,   // g1 x18 y24
0x28, 0x18,       // g0 x40 y24
0x8012,0x18,    // g1 x18 y24
0x28, 0x10,       // g0 x40 y16
0x8028, 0x18,   // g1 x40 y24
0x28, 0x10,       // g0 x40 y16
0x8012,0x10,    // g1 x18 y16
0x12, 0xa,         // g0 x18 y10
0x8012,0x10,    // g1 x18 y16
0x12,0xa,          // g0 x18 y10
0x8000, 0x14,   // g1 x0  y20

"

 Then the edges are sharp.
Is it possible to modify your converter to modify the code according to my template?

**Comment by jojoxyz** [comment]
I added to your code.
Gui open file / Save file / exit
You can put it in your git.

`from tkinter import *
from tkinter import filedialog

import math
import sys


################### converter ####################

def createObject(name, cmds):
  minx = miny = 10000000
  maxx = maxy = 0
  string = ""
  for cmd in cmds:
    if cmd[0] == 2:
      minx = min(minx,cmd[1])
      miny = min(miny,cmd[2])
      maxx = max(maxx,cmd[1])
      maxy = max(maxy,cmd[2])

  string += "const unsigned short draw_" + name + "[] PROGMEM = {\n";
  laserState = False
  
  biggestSide = max(maxx-minx, maxy-miny)
  # scale to the laser range
  scale = 1500. / biggestSide;
  print ("bounding box x: ", minx, maxx)
  print ("bounding box y: ", miny, maxy)
  print ("scale: ", scale)
  for cmd in cmds:
    if cmd[0] == 0:laserState = False
    if cmd[0] == 1:laserState = True
    if cmd[0] == 2:
      x = int(math.floor((cmd[1]-minx) * scale))
      y = int(math.floor((cmd[2]-miny) * scale))
      if laserState:
        x += 0x8000
      string += hex(x) + "," + hex(y) + ",\n"
  string += "};\n"
  return string
  
##################################################


#################### open file ###################
 
def openFile():
    tf = filedialog.askopenfilename(
        initialdir="C:/Users/MainFrame/Desktop/", 
        title="Open Text file", 
        filetypes=(("Text Files", "*.txt"),)
        )
    pathh.insert(END, tf)
    tf = open(tf)

    lines = tf.readlines()
    drawing = False 
    posx = posy = 0.

    cmds = [] 
    for l in lines:
      if l.startswith("G00"):
        if drawing: 
          cmds.append((0,))
        drawing = False 
      elif l.startswith("G01"):
        drawing = True 
        cmds.append((1,))
      elif l.startswith("X"):
        parts = l.split("Y")
        newposx = float(parts[0][1:])
        newposy = float(parts[1])
        cmds.append((2,newposx,newposy))
        posx = newposx
        posy = newposy

    result = createObject("object", cmds)

    file_cont = tf.read()                   # read converted result 
    txtarea.insert(END, result)             # write converted result to text space


    tf.close()

################################################


################ save file ####################

def saveFile():
    tf = filedialog.asksaveasfile(
        mode='w',

        title ="Save file",
        defaultextension=".cpp"
        )
   # tf.config(mode='w')

    pathh.insert(END, tf)
    result = str(txtarea.get(1.0, END))
    tf.write(result) 
   
    tf.close()


###############################################

ws = Tk()
ws.title("PythonGuides")
ws.geometry("400x500")
ws['bg']='#2a636e'

# adding frame
frame = Frame(ws)
frame.pack(pady=20)

# adding scrollbars 
ver_sb = Scrollbar(frame, orient=VERTICAL )
ver_sb.pack(side=RIGHT, fill=BOTH)

hor_sb = Scrollbar(frame, orient=HORIZONTAL)
hor_sb.pack(side=BOTTOM, fill=BOTH)

# adding writing space
txtarea = Text(frame, width=40, height=20)
txtarea.pack(side=LEFT)

# binding scrollbar with text area
txtarea.config(yscrollcommand=ver_sb.set)
ver_sb.config(command=txtarea.yview)

txtarea.config(xscrollcommand=hor_sb.set)
hor_sb.config(command=txtarea.xview)

# adding path showing box
pathh = Entry(ws)
pathh.pack(expand=True, fill=X, padx=10)

# adding buttons 
Button(
    ws, 
    text="Open File", 
    command=openFile
    ).pack(side=LEFT, expand=True, fill=X, padx=20)

Button(
    ws, 
    text="Save File", 
    command=saveFile
    ).pack(side=LEFT, expand=True, fill=X, padx=20)

Button(
    ws, 
    text="Exit", 
    command=lambda:ws.destroy()
    ).pack(side=LEFT, expand=True, fill=X, padx=20, pady=20)

ws.mainloop()`

**Comment by jojoxyz** [comment]
I added to your code.  Python3
Gui open file / Save file / exit

https://github.com/jojoxyz/convertGCode_GUI/blob/main/convertGCode_GUI.py
